site_name: Die Lernende Organisation im 21. Jahrhundert
site_url: https://simondueckert.github.io/
docs_dir: src
site_dir: ../docs/de

nav:
    - Willkommen: index.md
    - Die Vorgeschichte: 1-0-Prehistory.md
    - Die Geschichte: 2-0-Story.md
    - Mein Fazit: 3-0-Insight.md
    - Download:
      - PDF-Version: https://github.com/simondueckert/lernorg21/blob/master/de/build/lernorg21.pdf
      - Word-Version: https://github.com/simondueckert/lernorg21/blob/master/de/build/lernorg21.docx
      - HTML-Version: https://github.com/simondueckert/lernorg21/blob/master/de/build/lernorg21.html
      - E-Book (epub): https://github.com/simondueckert/lernorg21/blob/master/de/build/lernorg21.epub
    - Links:
      - cogneon.de: https://cogneon.de
      - CONNECT Community: https://community.cogneon.de

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
      primary: yellow
    scheme: default
    language: de
    icon:
      logo: material/star
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

repo_name: 'simondueckert/lernorg21'
repo_url: 'https://github.com/simondueckert/lernorg21'

extra:
    social:
        - icon: fontawesome/brands/mastodon
          link: 'https://colearn.social/@simondueckert'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/in/simondueckert/'
        - icon: fontawesome/brands/github
          link: 'https://github.com/simondueckert'
    disqus: lernos
    analytics:
       provider: custom
    generator: false

plugins:
  - search
